---
title: "README"
author: "john little"
date: "`r Sys.Date()`"
output: github_document
---

<!-- .md file is auto generate from the .Rmd file.  Do note edit the .md file.  Do edit and knit the .Rmd file -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This is an exploration of how to bootstrap an *Introduction to R* workshop for [Library Carpentry](https://librarycarpentry.org/)

## Assumption

- Library data is not unique
- Library data may have some consistently unique challenges
- Data Savvy skills should emphasize technique, tools, and approach

    - Techniques:  Reproducible, Scripting
    - Tools:  R / RStudio / Tidyverse
    - Approach:  Open Source and CC-BY are foundational.  
    
- For anyone intending to develop a core data savvy competency that extends beyond a comfortable beginner, using a fully capable data science scripting language is the best midterm to long-term investment from a skill building perspective. 
    
Narrative:  R has become and tool of choice for data science explorations.  **R** - a statistical programming language - and **Tidyverse** - a consistent way of applying and learning data science - are an excellent toolkit that can can be broadly applied to many advanced beginner to advanced intermediate data summation projects.  R, as a  tool, lends itself to portfolio building, to reproducible, to version control, to flexible and reproducible report writing, to generating various reports from one script, to web scraping and web publishing, and to extensible data savvy techniques.  The tool can have a steep learning curve but will carry a researcher farther entry level tools which are designed for easy of use but that quickly reach an efficiency barrier that is problematic for scalable sharing and collaborative coding.

## Process

1. Explore OpenRefine CrossRef dataset (exploring_crossref.Rmd)
1. Fork DataCarpentry's _R for Soc Sci_
1. Apply OpenRefine Examples over top of DC's _R for Soc Sci_
1. Pitch to A.Zoss
1. Pitch back to C.Eardman (meanwhile, CE will beging a loop in at his end)